dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "donsanjeewa-github"
    token:
      secure: "SONAR_TOKEN"
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
