dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "donsanjeewa-github"
      
language: php

before_script:
    - mysql -e 'CREATE DATABASE sms;'
    - cp .env.travis .env
    
# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm
script:
  - sonar-scanner -D sonar.login=$SONAR_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
