dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "donsanjeewa-github"
      
language: php

before_script:
    - cp .env.travis .env
    - mysql -e 'create database sms;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate --seed
    
# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm
script:
  - sonar-scanner -D sonar.login=$SONAR_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
